version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - cd src/greeter-api
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  exclude-paths:
    - node_modules/
  base-directory: src
  s3-prefix: greeter-api
