version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - cd src/greeter-api && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd src/greeter-api && npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/**/*
    - appspec.yml
  discard-paths: yes
